{ ... }:

# killy host — installer ISO configuration.
#
# This file is the only place you need to edit when adapting the installer
# for a new host. It wires up the shared base module (installer/base.nix)
# with the killy-specific files and names.
#
# To build the ISO:
#   cd ~/code/killy && nix-shell
#   build-iso          # → result/iso/killy-installer.iso
#
# To add a second host, copy this file to <host>/iso.nix, adjust every
# field below, and add a matching nixosConfigurations entry in flake.nix.

{
  imports = [ ../installer/base.nix ];

  # Hostname used in two places:
  #   - the path where per-host files are mounted on the live ISO
  #     (/etc/nixos/killy/wrapped-install-key.bin, etc.)
  #   - the PIV certificate CN searched by yk-unwrap.py
  #     (CN=killy-install-key)
  installer.hostname = "killy";

  # The Yubikey-wrapped age install key generated by scripts/yk-setup.py.
  # Safe to commit — it is AES-256-GCM encrypted to the Yubikey's on-device
  # P-256 key and cannot be decrypted without physical access to the Yubikey.
  installer.wrappedKey = ./wrapped-install-key.bin;

  # SOPS-encrypted host secrets (WiFi credentials, future install params).
  # Safe to commit — all sensitive fields are encrypted; only the install key,
  # operator key, or host key can decrypt them.
  installer.configFile = ./install-config.yaml;

  # Repository-level SOPS configuration: age recipient public keys and
  # creation rules. Embedded at /etc/nixos/.sops.yaml on the live ISO so
  # that `sops` commands work without manual configuration.
  installer.sopsYaml = ../.sops.yaml;

  # Python script that performs ECDH on-device via the Yubikey PIV interface
  # to recover the plaintext age install key. Called by yk-unwrap.service at
  # boot; also callable manually (see docs/user-guide.md).
  installer.unwrapScript = ../scripts/yk-unwrap.py;

  # Flake entry point for nixos-install (repo-level, shared across all hosts).
  installer.flakeSrc  = ../flake.nix;
  installer.flakeLock = ../flake.lock;

  # killy host OS configuration — embedded so nixos-install is self-contained.
  # hardware-configuration.nix is NOT embedded here; it is generated fresh by
  # killy-install at install time and copied into killy/system/ before nixos-install runs.
  environment.etc = {
    "nixos/killy/system/default.nix".source   = ./system/default.nix;
    "nixos/killy/system/base.nix".source      = ./system/base.nix;
    "nixos/killy/system/wireguard.nix".source = ./system/wireguard.nix;
    "nixos/killy/system/virt.nix".source      = ./system/virt.nix;
  };

  # Output ISO file name and volume label (visible in boot menus and when
  # the drive is mounted on another machine).
  isoImage.isoName  = "killy-installer.iso";
  isoImage.volumeID = "KILLY_INSTALLER";
}
